# Generated by Django 4.2 on 2026-04-17 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255)),
                ('days_remaining', models.IntegerField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('platform', 'Platform (in-site)')], default='email', max_length=20)),
                ('sent_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ประวัติการแจ้งเตือน',
                'verbose_name_plural': 'ประวัติการแจ้งเตือน',
                'ordering': ['-sent_at'],
            },
        ),
    ]
