# Generated by Django 4.2 on 2026-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFilterRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_key', models.CharField(max_length=50, unique=True)),
                ('display_name_th', models.CharField(max_length=100, verbose_name='ชื่อแสดงผล (ภาษาไทย)')),
                ('python_class_path', models.CharField(help_text='e.g. military_reports.filters.rank_filter.RankFilter', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ตัวกรองการค้นหา',
                'verbose_name_plural': 'ตัวกรองการค้นหา',
                'ordering': ['sort_order', 'display_name_th'],
            },
        ),
    ]
