# Generated by Django 4.2 on 2026-04-17 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Course ID (edX)')),
                ('course_name', models.CharField(max_length=500, verbose_name='ชื่อหลักสูตร/รายวิชา')),
                ('validity_years', models.PositiveSmallIntegerField(default=3, verbose_name='อายุใบประกาศ (ปี)')),
                ('allow_renewal_exam', models.BooleanField(default=True, verbose_name='อนุญาตให้ทำแบบทดสอบต่ออายุ')),
                ('renewal_exam_block_id', models.CharField(blank=True, default='', max_length=500, verbose_name='Block ID ของแบบทดสอบต่ออายุ')),
                ('renewal_passing_score', models.PositiveSmallIntegerField(default=80, verbose_name='คะแนนผ่านแบบทดสอบต่ออายุ (%)')),
            ],
            options={
                'verbose_name': 'การตั้งค่าอายุใบประกาศ',
                'verbose_name_plural': 'การตั้งค่าอายุใบประกาศ',
            },
        ),
        migrations.CreateModel(
            name='UserCertificateExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('issued_date', models.DateField(verbose_name='วันที่ออกใบประกาศ')),
                ('expiry_date', models.DateField(db_index=True, verbose_name='วันหมดอายุ')),
                ('status', models.CharField(choices=[('active', 'ยังไม่หมดอายุ'), ('expired', 'หมดอายุแล้ว'), ('renewed', 'ต่ออายุแล้ว'), ('revoked', 'ถูกเพิกถอน')], db_index=True, default='active', max_length=10)),
                ('renewal_count', models.PositiveSmallIntegerField(default=0, verbose_name='จำนวนครั้งที่ต่ออายุ')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_expiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'วันหมดอายุใบประกาศของผู้เรียน',
                'verbose_name_plural': 'วันหมดอายุใบประกาศของผู้เรียน',
            },
        ),
        migrations.CreateModel(
            name='CertificateRenewalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255)),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('exam', 'แบบทดสอบต่ออายุ'), ('retake', 'เรียนใหม่ทั้งหลักสูตร')], max_length=10)),
                ('score', models.FloatField(blank=True, null=True, verbose_name='คะแนนแบบทดสอบ (%)')),
                ('previous_expiry_date', models.DateField()),
                ('new_expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ประวัติการต่ออายุใบประกาศ',
                'verbose_name_plural': 'ประวัติการต่ออายุใบประกาศ',
                'ordering': ['-renewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usercertificateexpiry',
            index=models.Index(fields=['expiry_date', 'status'], name='certificate_expiry__cdceab_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertificateexpiry',
            index=models.Index(fields=['course_id', 'status'], name='certificate_course__38b1d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercertificateexpiry',
            unique_together={('user', 'course_id')},
        ),
    ]
