# Generated by Django 4.2 on 2026-09-24 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('military_profile', '0021_militaryuserprofile_new_curriculum_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อหลักสูตร')),
                ('batch_code', models.CharField(max_length=50, verbose_name='รุ่นที่')),
                ('academic_year', models.PositiveIntegerField(db_index=True, verbose_name='ปีการศึกษา (พ.ศ.)')),
                ('eligible_rank_class', models.CharField(blank=True, default='', max_length=100, verbose_name='ช่วงชั้นยศที่มีสิทธิ์')),
                ('eligible_personnel_type', models.CharField(blank=True, default='', max_length=100, verbose_name='ประเภทบุคลากรที่มีสิทธิ์')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('submitted', 'ส่งให้แผนกเตรียมพล'), ('active', 'ใช้งาน'), ('closed', 'ปิดรุ่น')], db_index=True, default='draft', max_length=20, verbose_name='สถานะ')),
                ('quota_total', models.PositiveIntegerField(default=0, verbose_name='โควตารวม (ส่วนกลาง)')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ส่งให้แผนกเตรียมพล')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='military_profile.organization', verbose_name='หน่วยงานผู้จัด')),
            ],
            options={
                'verbose_name': 'หลักสูตรประจำปี/รุ่น',
                'verbose_name_plural': 'หลักสูตรประจำปี/รุ่น',
                'ordering': ['-academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255, verbose_name='Course ID (edX)')),
                ('display_name', models.CharField(max_length=255, verbose_name='ชื่อวิชา')),
                ('sequence_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับในหลักสูตร')),
                ('credit_hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='จำนวนชั่วโมง')),
                ('credits', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='หน่วยกิต')),
                ('assessment_type', models.CharField(choices=[('score', 'คะแนน/เกรด'), ('pass_fail', 'ผ่าน/ไม่ผ่าน')], default='score', max_length=20, verbose_name='ประเภทการวัดผล')),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='คะแนนผ่าน (ใช้เมื่อ assessment_type=score)')),
                ('is_required', models.BooleanField(default=True, verbose_name='วิชาบังคับ')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='military_curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'วิชาในหลักสูตร',
                'verbose_name_plural': 'วิชาในหลักสูตร',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('course', 'รายวิชา'), ('curriculum', 'หลักสูตรรวม')], max_length=20, verbose_name='ระดับการประเมิน')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อแบบประเมิน')),
                ('schema', models.JSONField(verbose_name='โครงสร้างคำถาม')),
                ('is_required', models.BooleanField(default=True, verbose_name='บังคับประเมิน (ใช้เป็น gate)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_forms_created', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_forms', to='military_curriculum.curriculum')),
                ('curriculum_course', models.ForeignKey(blank=True, help_text='null เมื่อ level=curriculum', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_forms', to='military_curriculum.curriculumcourse')),
            ],
            options={
                'verbose_name': 'แบบประเมิน',
                'verbose_name_plural': 'แบบประเมิน',
            },
        ),
        migrations.CreateModel(
            name='ManualGradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=255, verbose_name='รายการคะแนน')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='คะแนนที่ได้')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='คะแนนเต็ม')),
                ('weight', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='น้ำหนัก % เทียบกับคะแนนอัตโนมัติ')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_grades', to='military_curriculum.curriculumcourse')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_grades_entered', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'คะแนนกรอกเอง',
                'verbose_name_plural': 'คะแนนกรอกเอง',
            },
        ),
        migrations.CreateModel(
            name='FinalCourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='คะแนนสรุป')),
                ('passed', models.BooleanField(null=True, verbose_name='ผ่าน (None = ยังไม่ตัดสิน)')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_results_computed', to=settings.AUTH_USER_MODEL)),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='military_curriculum.curriculumcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_course_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ผลการเรียนสรุปรายวิชา',
                'verbose_name_plural': 'ผลการเรียนสรุปรายวิชา',
            },
        ),
        migrations.CreateModel(
            name='EvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='military_curriculum.evaluationform')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'คำตอบแบบประเมิน',
                'verbose_name_plural': 'คำตอบแบบประเมิน',
            },
        ),
        migrations.CreateModel(
            name='CurriculumRegionQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_region', models.CharField(max_length=10, verbose_name='กองทัพภาค')),
                ('quota', models.PositiveIntegerField(default=0, verbose_name='โควตา')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_quotas', to='military_curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'โควตาตามกองทัพภาค',
                'verbose_name_plural': 'โควตาตามกองทัพภาค',
            },
        ),
        migrations.CreateModel(
            name='CurriculumEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('processing', 'กำลังลงทะเบียน'), ('completed', 'สำเร็จ'), ('partial_failed', 'สำเร็จบางส่วน'), ('failed', 'ล้มเหลว')], db_index=True, default='pending', max_length=20)),
                ('result_detail', models.JSONField(blank=True, default=dict, help_text='{"course_id": "enrolled" | "failed: <เหตุผล>"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_requests', to='military_curriculum.curriculum')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_enrollments_requested', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งบรรจุ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_enrollment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'คำขอบรรจุเข้าหลักสูตร',
                'verbose_name_plural': 'คำขอบรรจุเข้าหลักสูตร',
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='เจ้าของวิชา')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='co_instructors_added', to=settings.AUTH_USER_MODEL)),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='military_curriculum.curriculumcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_instructor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ผู้สอนประจำวิชา',
                'verbose_name_plural': 'ผู้สอนประจำวิชา',
            },
        ),
        migrations.AddIndex(
            model_name='manualgradeentry',
            index=models.Index(fields=['curriculum_course', 'student'], name='military_cu_curricu_cd61ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='finalcourseresult',
            unique_together={('curriculum_course', 'student')},
        ),
        migrations.AddIndex(
            model_name='evaluationresponse',
            index=models.Index(fields=['student', 'form'], name='military_cu_student_729963_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationresponse',
            unique_together={('form', 'student')},
        ),
        migrations.AddConstraint(
            model_name='evaluationform',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('curriculum_course__isnull', True), ('level', 'curriculum')), models.Q(('curriculum_course__isnull', False), ('level', 'course')), _connector='OR'), name='evaluation_form_level_consistency'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumregionquota',
            unique_together={('curriculum', 'army_region')},
        ),
        migrations.AddIndex(
            model_name='curriculumenrollmentrequest',
            index=models.Index(fields=['status', 'created_at'], name='military_cu_status_8da45b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumenrollmentrequest',
            unique_together={('curriculum', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcourseinstructor',
            unique_together={('curriculum_course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcourse',
            unique_together={('curriculum', 'course_id')},
        ),
        migrations.AddIndex(
            model_name='curriculum',
            index=models.Index(fields=['academic_year', 'status'], name='military_cu_academi_6be546_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('name', 'batch_code', 'academic_year')},
        ),
    ]
