# Generated by Django 4.2 on 2026-09-28 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('military_curriculum', '0004_curriculum_start_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='category',
            field=models.CharField(blank=True, choices=[('nco_basic', 'นายสิบชั้นต้น'), ('nco_senior', 'นายสิบชั้นสูง (อาวุโส)'), ('officer_company', 'นายทหารสัญญาบัตร ชั้นนายร้อย'), ('officer_field', 'นายทหารสัญญาบัตร ชั้นนายพัน'), ('officer_senior', 'นายทหารสัญญาบัตร ชั้นนายพล/เสนาธิการ'), ('other', 'อื่นๆ')], default='', help_text='ใช้จับคู่ว่าหลักสูตรนี้เป็นประเภทเดียวกับหลักสูตรอื่นไหม (ชื่อ/รุ่นต่างกันได้ แต่ category เดียวกัน) สำหรับ prerequisite', max_length=30, verbose_name='ประเภทหลักสูตร'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='eligible_prerequisite_categories',
            field=models.JSONField(blank=True, default=list, help_text='list ของ category code เช่น ["nco_basic"] — ว่าง = ไม่มีเงื่อนไขนี้', verbose_name='ต้องผ่านหลักสูตรประเภทใดมาก่อน'),
        ),
        migrations.CreateModel(
            name='LegacyCurriculumCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nco_basic', 'นายสิบชั้นต้น'), ('nco_senior', 'นายสิบชั้นสูง (อาวุโส)'), ('officer_company', 'นายทหารสัญญาบัตร ชั้นนายร้อย'), ('officer_field', 'นายทหารสัญญาบัตร ชั้นนายพัน'), ('officer_senior', 'นายทหารสัญญาบัตร ชั้นนายพล/เสนาธิการ'), ('other', 'อื่นๆ')], max_length=30, verbose_name='ประเภทหลักสูตรที่เคยผ่าน')),
                ('note', models.CharField(blank=True, default='', help_text='เช่น ปีที่จบ/ชื่อหลักสูตรที่เรียนตอนนั้น', max_length=255, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_completions_recorded', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_curriculum_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ประวัติผ่านหลักสูตรก่อนมีระบบ',
                'verbose_name_plural': 'ประวัติผ่านหลักสูตรก่อนมีระบบ',
                'unique_together': {('student', 'category')},
            },
        ),
    ]
