# Generated by Django 4.2 on 2026-09-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_curriculum', '0005_curriculum_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcourseinstructor',
            name='topic_note',
            field=models.CharField(blank=True, default='', help_text='ป้ายกำกับอิสระ ไม่ผูกกับสิทธิ์การเข้าถึงจริง (ผู้ช่วยสอนทุกคนยังเห็น/ให้คะแนนได้ทุกคนในวิชานี้เท่ากันหมด) — ใช้ตอนวิชาเดียวรวมหลายหัวข้อย่อยที่มีผู้รับผิดชอบต่างกัน เพื่อให้รู้ว่าใครดูแลส่วนไหนโดยไม่ต้องแยกวิชาจริงในระบบ', max_length=255, verbose_name='หัวข้อ/ความรับผิดชอบ'),
        ),
    ]
