# Generated by Django 4.2 on 2026-09-30 05:57
#
# แยกออกมาเป็นไฟล์ของตัวเองเฉพาะ 2 field ใหม่ที่ไม่มีการเปลี่ยนชนิดข้อมูลเดิม
# (ปลอดภัย ไม่กระทบข้อมูลเดิมเลย) — ส่วนที่เปลี่ยนชนิดฟิลด์เดิม (CharField ->
# JSONField) แยกไปอยู่ 0008 เพราะต้องใช้วิธี add-new/remove-old/rename แทนการ
# AlterField ตรงๆ (ดู docstring ใน 0008 สำหรับเหตุผล: บน MySQL ของ production
# จริง ALTER COLUMN ... MODIFY JSON ไม่ auto-cast ค่า string เดิมให้เป็น JSON
# เหมือน Postgres ทำให้ AlterField ตรงๆ ทำให้ migrate ล้มเหลวกลางคัน)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_curriculum', '0006_curriculumcourseinstructor_topic_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='eligible_branch',
            field=models.CharField(blank=True, choices=[('signal', 'เหล่า ส.'), ('any', 'ไม่จำกัดเหล่า'), ('unspecified', 'ไม่ระบุ')], default='', max_length=20, verbose_name='เหล่าที่มีสิทธิ์'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='training_purpose',
            field=models.CharField(blank=True, choices=[('production', 'หลักสูตรผลิต'), ('career_track', 'หลักสูตรตามแนวทางรับราชการ'), ('skill_enrichment', 'หลักสูตรเพิ่มพูนความรู้'), ('special_external_budget', 'หลักสูตรพิเศษ (ใช้งบประมาณจากภายนอก)')], default='', help_text='การจัดประเภทตามเกณฑ์ของแผนกเตรียมการ (ผลิต/ตามแนวทางรับราชการ/เพิ่มพูนความรู้/พิเศษ) — ไม่เกี่ยวกับ category ด้านบน', max_length=30, verbose_name='ประเภทหลักสูตร (แผนกเตรียมการ)'),
        ),
    ]
