# Generated by Django 4.2 on 2026-09-30 05:57
#
# ข้อควรระวังตอนเขียนด้วยมือเพิ่มจาก makemigrations เดิม: eligible_personnel_type
# และ eligible_rank_class เปลี่ยนชนิดจาก CharField (string เดี่ยว) เป็น
# JSONField (list) — Postgres จะ cast ค่าเดิมด้วย to_jsonb() ตอน AlterField
# ทำให้ค่าเดิม "military" กลายเป็น JSON scalar string "military" (ไม่ใช่ list
# ["military"]) ต้องมี RunPython แปลงข้อมูลต่ออีกชั้นหลัง AlterField แต่ละฟิลด์
# — ส่วน eligible_prerequisite_categories เป็น JSONField(list) อยู่แล้วทั้งก่อน
# และหลัง (แค่เปลี่ยน element จาก str เป็น dict) ไม่มีการ cast ระดับ DB แต่ก็
# ยังต้อง RunPython แปลง element เช่นกัน

from django.db import migrations, models


def _personnel_type_to_list(apps, schema_editor):
    Curriculum = apps.get_model("military_curriculum", "Curriculum")
    for c in Curriculum.objects.all().iterator():
        raw = c.eligible_personnel_type
        if isinstance(raw, list):
            continue
        Curriculum.objects.filter(pk=c.pk).update(eligible_personnel_type=[raw] if raw else [])


def _personnel_type_to_string(apps, schema_editor):
    Curriculum = apps.get_model("military_curriculum", "Curriculum")
    for c in Curriculum.objects.all().iterator():
        raw = c.eligible_personnel_type
        if isinstance(raw, list):
            Curriculum.objects.filter(pk=c.pk).update(eligible_personnel_type=raw[0] if raw else "")


def _rank_class_to_list(apps, schema_editor):
    Curriculum = apps.get_model("military_curriculum", "Curriculum")
    for c in Curriculum.objects.all().iterator():
        raw = c.eligible_rank_class
        if isinstance(raw, list):
            continue
        Curriculum.objects.filter(pk=c.pk).update(eligible_rank_class=[raw] if raw else [])


def _rank_class_to_string(apps, schema_editor):
    Curriculum = apps.get_model("military_curriculum", "Curriculum")
    for c in Curriculum.objects.all().iterator():
        raw = c.eligible_rank_class
        if isinstance(raw, list):
            Curriculum.objects.filter(pk=c.pk).update(eligible_rank_class=raw[0] if raw else "")


def _prerequisite_categories_to_dicts(apps, schema_editor):
    Curriculum = apps.get_model("military_curriculum", "Curriculum")
    for c in Curriculum.objects.all().iterator():
        raw = c.eligible_prerequisite_categories or []
        if raw and isinstance(raw[0], dict):
            continue
        new_value = [{"category": code, "min_years_since": None} for code in raw]
        Curriculum.objects.filter(pk=c.pk).update(eligible_prerequisite_categories=new_value)


def _prerequisite_categories_to_strings(apps, schema_editor):
    Curriculum = apps.get_model("military_curriculum", "Curriculum")
    for c in Curriculum.objects.all().iterator():
        raw = c.eligible_prerequisite_categories or []
        if raw and isinstance(raw[0], dict):
            new_value = [item.get("category") for item in raw if item.get("category")]
            Curriculum.objects.filter(pk=c.pk).update(eligible_prerequisite_categories=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('military_curriculum', '0006_curriculumcourseinstructor_topic_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='eligible_branch',
            field=models.CharField(blank=True, choices=[('signal', 'เหล่า ส.'), ('any', 'ไม่จำกัดเหล่า'), ('unspecified', 'ไม่ระบุ')], default='', max_length=20, verbose_name='เหล่าที่มีสิทธิ์'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='training_purpose',
            field=models.CharField(blank=True, choices=[('production', 'หลักสูตรผลิต'), ('career_track', 'หลักสูตรตามแนวทางรับราชการ'), ('skill_enrichment', 'หลักสูตรเพิ่มพูนความรู้'), ('special_external_budget', 'หลักสูตรพิเศษ (ใช้งบประมาณจากภายนอก)')], default='', help_text='การจัดประเภทตามเกณฑ์ของแผนกเตรียมการ (ผลิต/ตามแนวทางรับราชการ/เพิ่มพูนความรู้/พิเศษ) — ไม่เกี่ยวกับ category ด้านบน', max_length=30, verbose_name='ประเภทหลักสูตร (แผนกเตรียมการ)'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='category',
            field=models.CharField(blank=True, choices=[('nco_basic', 'นายสิบชั้นต้น'), ('nco_senior', 'นายสิบชั้นสูง (อาวุโส)'), ('officer_company', 'นายทหารสัญญาบัตร ชั้นนายร้อย'), ('officer_field', 'นายทหารสัญญาบัตร ชั้นนายพัน'), ('officer_senior', 'นายทหารสัญญาบัตร ชั้นนายพล/เสนาธิการ'), ('other', 'อื่นๆ')], default='', help_text='ใช้จับคู่ว่าหลักสูตรนี้เป็นประเภทเดียวกับหลักสูตรอื่นไหม (ชื่อ/รุ่นต่างกันได้ แต่ category เดียวกัน) สำหรับ prerequisite เท่านั้น — คนละเรื่องกับ training_purpose ด้านล่าง', max_length=30, verbose_name='ประเภทหลักสูตร (สำหรับจับคู่ prerequisite)'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='eligible_min_years_in_rank',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ไม่แสดงในฟอร์มสร้าง/แก้ไขแล้วตามคำขอของแผนกเตรียมการ (ไม่ได้ใช้งานจริง) แต่คงไว้เพราะรายงานความคับคั่งยังอ้างอิงอยู่', null=True, verbose_name='ระยะเวลาครองยศขั้นต่ำ (ปี)'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='eligible_personnel_type',
            field=models.JSONField(blank=True, default=list, help_text='list ของ PERSONNEL_TYPE_CHOICES code เช่น ["military","civilian"]', verbose_name='ประเภทบุคลากรที่มีสิทธิ์'),
        ),
        migrations.RunPython(_personnel_type_to_list, _personnel_type_to_string),
        migrations.AlterField(
            model_name='curriculum',
            name='eligible_prerequisite_categories',
            field=models.JSONField(blank=True, default=list, help_text='list ของ {"category": code, "min_years_since": int|None} เช่น [{"category": "nco_basic", "min_years_since": 2}] — min_years_since ว่าง/None = ไม่มีเงื่อนไขปี, list ว่าง = ไม่มีเงื่อนไขนี้เลย', verbose_name='ต้องผ่านหลักสูตรประเภทใดมาก่อน'),
        ),
        migrations.RunPython(_prerequisite_categories_to_dicts, _prerequisite_categories_to_strings),
        migrations.AlterField(
            model_name='curriculum',
            name='eligible_rank_class',
            field=models.JSONField(blank=True, default=list, help_text='list ของคำอธิบายแต่ละข้อ เช่น ["ผ่านการฝึกภาคสนามมาก่อน"]', verbose_name='คุณสมบัติผู้รับการฝึกอบรม (รายข้อ)'),
        ),
        migrations.RunPython(_rank_class_to_list, _rank_class_to_string),
        migrations.AlterField(
            model_name='curriculum',
            name='eligible_rank_max',
            field=models.CharField(blank=True, choices=[('NNS', 'นนส. (นักเรียนนายสิบ)'), ('PVT', 'พลทหาร'), ('CPL', 'สิบตรี'), ('SGT3', 'สิบโท'), ('SGT2', 'สิบเอก'), ('SSGT', 'จ่าสิบตรี'), ('MSGT', 'จ่าสิบโท'), ('CSGT', 'จ่าสิบเอก'), ('CSGT_S', 'จ่าสิบเอกพิเศษ'), ('WO1', 'พันจ่าตรี'), ('WO2', 'พันจ่าโท'), ('WO3', 'พันจ่าเอก'), ('2LT', 'ร้อยตรี'), ('1LT', 'ร้อยโท'), ('CPT', 'ร้อยเอก'), ('MAJ', 'พันตรี'), ('LTCOL', 'พันโท'), ('COL', 'พันเอก'), ('COL_S', 'พันเอกพิเศษ'), ('BGEN', 'พลตรี'), ('MGEN', 'พลโท'), ('GEN', 'พลเอก')], default='', max_length=10, verbose_name='ยศสูงสุดที่มีสิทธิ์'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='eligible_rank_min',
            field=models.CharField(blank=True, choices=[('NNS', 'นนส. (นักเรียนนายสิบ)'), ('PVT', 'พลทหาร'), ('CPL', 'สิบตรี'), ('SGT3', 'สิบโท'), ('SGT2', 'สิบเอก'), ('SSGT', 'จ่าสิบตรี'), ('MSGT', 'จ่าสิบโท'), ('CSGT', 'จ่าสิบเอก'), ('CSGT_S', 'จ่าสิบเอกพิเศษ'), ('WO1', 'พันจ่าตรี'), ('WO2', 'พันจ่าโท'), ('WO3', 'พันจ่าเอก'), ('2LT', 'ร้อยตรี'), ('1LT', 'ร้อยโท'), ('CPT', 'ร้อยเอก'), ('MAJ', 'พันตรี'), ('LTCOL', 'พันโท'), ('COL', 'พันเอก'), ('COL_S', 'พันเอกพิเศษ'), ('BGEN', 'พลตรี'), ('MGEN', 'พลโท'), ('GEN', 'พลเอก')], default='', max_length=10, verbose_name='ยศต่ำสุดที่มีสิทธิ์'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='quota_total',
            field=models.PositiveIntegerField(default=0, verbose_name='ยอดผู้เข้ารับการฝึกอบรมตามแผน'),
        ),
    ]
