# Generated by Django 4.2 on 2026-09-30 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('military_profile', '0022_militaryuserprofile_rank_effective_date'),
        ('military_curriculum', '0008_curriculum_json_fields_mysql_safe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อแม่แบบ')),
                ('eligible_rank_class', models.JSONField(blank=True, default=list, verbose_name='คุณสมบัติผู้รับการฝึกอบรม (รายข้อ)')),
                ('eligible_rank_min', models.CharField(blank=True, choices=[('NNS', 'นนส. (นักเรียนนายสิบ)'), ('PVT', 'พลทหาร'), ('CPL', 'สิบตรี'), ('SGT3', 'สิบโท'), ('SGT2', 'สิบเอก'), ('SSGT', 'จ่าสิบตรี'), ('MSGT', 'จ่าสิบโท'), ('CSGT', 'จ่าสิบเอก'), ('CSGT_S', 'จ่าสิบเอกพิเศษ'), ('WO1', 'พันจ่าตรี'), ('WO2', 'พันจ่าโท'), ('WO3', 'พันจ่าเอก'), ('2LT', 'ร้อยตรี'), ('1LT', 'ร้อยโท'), ('CPT', 'ร้อยเอก'), ('MAJ', 'พันตรี'), ('LTCOL', 'พันโท'), ('COL', 'พันเอก'), ('COL_S', 'พันเอกพิเศษ'), ('BGEN', 'พลตรี'), ('MGEN', 'พลโท'), ('GEN', 'พลเอก')], default='', max_length=10, verbose_name='ยศต่ำสุดที่มีสิทธิ์')),
                ('eligible_rank_max', models.CharField(blank=True, choices=[('NNS', 'นนส. (นักเรียนนายสิบ)'), ('PVT', 'พลทหาร'), ('CPL', 'สิบตรี'), ('SGT3', 'สิบโท'), ('SGT2', 'สิบเอก'), ('SSGT', 'จ่าสิบตรี'), ('MSGT', 'จ่าสิบโท'), ('CSGT', 'จ่าสิบเอก'), ('CSGT_S', 'จ่าสิบเอกพิเศษ'), ('WO1', 'พันจ่าตรี'), ('WO2', 'พันจ่าโท'), ('WO3', 'พันจ่าเอก'), ('2LT', 'ร้อยตรี'), ('1LT', 'ร้อยโท'), ('CPT', 'ร้อยเอก'), ('MAJ', 'พันตรี'), ('LTCOL', 'พันโท'), ('COL', 'พันเอก'), ('COL_S', 'พันเอกพิเศษ'), ('BGEN', 'พลตรี'), ('MGEN', 'พลโท'), ('GEN', 'พลเอก')], default='', max_length=10, verbose_name='ยศสูงสุดที่มีสิทธิ์')),
                ('eligible_branch', models.CharField(blank=True, choices=[('signal', 'เหล่า ส.'), ('any', 'ไม่จำกัดเหล่า'), ('unspecified', 'ไม่ระบุ')], default='', max_length=20, verbose_name='เหล่าที่มีสิทธิ์')),
                ('eligible_personnel_type', models.JSONField(blank=True, default=list, verbose_name='ประเภทบุคลากรที่มีสิทธิ์')),
                ('eligible_min_years_in_rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ระยะเวลาครองยศขั้นต่ำ (ปี)')),
                ('category', models.CharField(blank=True, choices=[('nco_basic', 'นายสิบชั้นต้น'), ('nco_senior', 'นายสิบชั้นสูง (อาวุโส)'), ('officer_company', 'นายทหารสัญญาบัตร ชั้นนายร้อย'), ('officer_field', 'นายทหารสัญญาบัตร ชั้นนายพัน'), ('officer_senior', 'นายทหารสัญญาบัตร ชั้นนายพล/เสนาธิการ'), ('other', 'อื่นๆ')], default='', max_length=30, verbose_name='ประเภทหลักสูตร (สำหรับจับคู่ prerequisite)')),
                ('training_purpose', models.CharField(blank=True, choices=[('production', 'หลักสูตรผลิต'), ('career_track', 'หลักสูตรตามแนวทางรับราชการ'), ('skill_enrichment', 'หลักสูตรเพิ่มพูนความรู้'), ('special_external_budget', 'หลักสูตรพิเศษ (ใช้งบประมาณจากภายนอก)')], default='', max_length=30, verbose_name='ประเภทหลักสูตร (แผนกเตรียมการ)')),
                ('eligible_prerequisite_categories', models.JSONField(blank=True, default=list, verbose_name='ต้องผ่านหลักสูตรประเภทใดมาก่อน')),
                ('quota_total', models.PositiveIntegerField(default=0, verbose_name='ยอดผู้เข้ารับการฝึกอบรมตามแผน (ค่าแนะนำ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_templates', to='military_profile.organization', verbose_name='หน่วยงานเจ้าของแม่แบบ')),
            ],
            options={
                'verbose_name': 'แม่แบบหลักสูตร',
                'verbose_name_plural': 'แม่แบบหลักสูตร',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumTemplateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255, verbose_name='Course ID (edX)')),
                ('display_name', models.CharField(max_length=255, verbose_name='ชื่อวิชา')),
                ('sequence_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับในหลักสูตร')),
                ('credit_hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='จำนวนชั่วโมง')),
                ('credits', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='หน่วยกิต')),
                ('assessment_type', models.CharField(choices=[('score', 'คะแนน/เกรด'), ('pass_fail', 'ผ่าน/ไม่ผ่าน')], default='score', max_length=20, verbose_name='ประเภทการวัดผล')),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='คะแนนผ่าน')),
                ('is_required', models.BooleanField(default=True, verbose_name='วิชาบังคับ')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='military_curriculum.curriculumtemplate')),
            ],
            options={
                'verbose_name': 'วิชาในแม่แบบหลักสูตร',
                'verbose_name_plural': 'วิชาในแม่แบบหลักสูตร',
                'ordering': ['sequence_order'],
                'unique_together': {('template', 'course_id')},
            },
        ),
    ]
