import type { Metadata } from "next";
import { Noto_Sans_Thai, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import SessionTimeout from "@/components/SessionTimeout";
import CapacityExceededModal from "@/components/CapacityExceededModal";
import ActiveUserHeartbeat from "@/components/ActiveUserHeartbeat";

// globals.css เคยอ้างอิง 'Sarabun' เป็น body font แต่ไม่เคยโหลดจริง (ไม่มี
// next/font/@font-face/<link> ที่ไหนเลย) ข้อความไทยทั้งระบบ fallback ไป
// Arial/system font เงียบๆ มาตลอด — โหลด Noto Sans Thai จริงแทน
const notoSansThai = Noto_Sans_Thai({
  variable: "--font-body",
  subsets: ["thai", "latin"],
  weight: ["400", "500", "600", "700"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono-signal",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Signal Standard Elearning",
  description: "Generated by Signalschool",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
      className={`${notoSansThai.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <SessionTimeout />
        <CapacityExceededModal />
        <ActiveUserHeartbeat />
      </body>
    </html>
  );
}
