# Generated by Django 4.2 on 2026-04-17 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_encrypted', models.CharField(db_index=True, max_length=500, unique=True)),
                ('military_id_encrypted', models.CharField(max_length=500)),
                ('full_name_th', models.CharField(max_length=255, verbose_name='ชื่อ-นามสกุล (ภาษาไทย)')),
                ('rank', models.CharField(choices=[('PVT', 'พลทหาร'), ('CPL', 'สิบตรี'), ('SGT3', 'สิบโท'), ('SGT2', 'สิบเอก'), ('SSGT', 'จ่าสิบตรี'), ('MSGT', 'จ่าสิบโท'), ('CSGT', 'จ่าสิบเอก'), ('WO1', 'พันจ่าตรี'), ('WO2', 'พันจ่าโท'), ('WO3', 'พันจ่าเอก'), ('2LT', 'ร้อยตรี'), ('1LT', 'ร้อยโท'), ('CPT', 'ร้อยเอก'), ('MAJ', 'พันตรี'), ('LTCOL', 'พันโท'), ('COL', 'พันเอก'), ('BGEN', 'พลตรี'), ('MGEN', 'พลโท'), ('GEN', 'พลเอก')], max_length=10, verbose_name='ชั้นยศ')),
                ('unit', models.CharField(max_length=255, verbose_name='หน่วยต้นสังกัด')),
                ('sub_unit', models.CharField(blank=True, default='', max_length=255, verbose_name='หน่วยรอง')),
                ('service_start_date', models.DateField(verbose_name='วันเริ่มรับราชการ')),
                ('birth_date', models.DateField(verbose_name='วันเกิด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='military_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ข้อมูลบุคลากรทหาร',
                'verbose_name_plural': 'ข้อมูลบุคลากรทหาร',
            },
        ),
        migrations.AddIndex(
            model_name='militaryuserprofile',
            index=models.Index(fields=['unit'], name='military_pr_unit_c77746_idx'),
        ),
        migrations.AddIndex(
            model_name='militaryuserprofile',
            index=models.Index(fields=['rank'], name='military_pr_rank_b342d6_idx'),
        ),
    ]
