# Generated by Django 5.2.11 on 2026-05-28 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_profile', '0007_course_requirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateApprovalBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อรอบ')),
                ('course_id', models.CharField(db_index=True, max_length=255, verbose_name='Course ID')),
                ('course_name', models.CharField(blank=True, max_length=500, verbose_name='ชื่อหลักสูตร')),
                ('enrollment_start', models.DateField(verbose_name='เปิดรับเรียน')),
                ('enrollment_end', models.DateField(verbose_name='ปิดรับเรียน / สอบ')),
                ('approve_date', models.DateField(verbose_name='วันที่อนุมัติใบประกาศ')),
                ('status', models.CharField(choices=[('open', 'รับสมัคร / รอผล'), ('approved', 'อนุมัติแล้ว'), ('closed', 'ปิดรอบ')], db_index=True, default='open', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่อนุมัติ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รอบการอนุมัติใบประกาศ',
                'verbose_name_plural': 'รอบการอนุมัติใบประกาศ',
                'ordering': ['-approve_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificatePendingApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_at', models.DateTimeField(verbose_name='วันที่ผ่าน')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='คะแนน (%)')),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่ผ่าน / ปฏิเสธ')], db_index=True, default='pending', max_length=20)),
                ('cert_uuid', models.CharField(blank=True, max_length=50, verbose_name='UUID ใบประกาศ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ผู้รออนุมัติใบประกาศ',
                'verbose_name_plural': 'ผู้รออนุมัติใบประกาศ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='militaryuserprofile',
            new_name='military_pr_army_re_f39fcb_idx',
            old_fields=('army_region', 'rank'),
        ),
        migrations.AlterField(
            model_name='courserequirement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='militaryuserprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='militaryuserprofile',
            name='national_id_hmac',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificateapprovalbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_batches_approved', to=settings.AUTH_USER_MODEL, verbose_name='อนุมัติโดย'),
        ),
        migrations.AddField(
            model_name='certificateapprovalbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_batches_created', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย'),
        ),
        migrations.AddField(
            model_name='certificatependingapproval',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approvals', to='military_profile.certificateapprovalbatch', verbose_name='รอบ'),
        ),
        migrations.AddField(
            model_name='certificatependingapproval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_pending_approvals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เรียน'),
        ),
        migrations.AlterUniqueTogether(
            name='certificatependingapproval',
            unique_together={('batch', 'user')},
        ),
    ]
