# Generated by Django 5.2.11 on 2026-05-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_profile', '0008_certificateapprovalbatch_certificatependingapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryuserprofile',
            name='civilian_prefix',
            field=models.CharField(blank=True, choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], default='', max_length=10, verbose_name='คำนำหน้า'),
        ),
        migrations.AddField(
            model_name='militaryuserprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง')], default='M', max_length=1, verbose_name='เพศ'),
        ),
        migrations.AddField(
            model_name='militaryuserprofile',
            name='personnel_type',
            field=models.CharField(choices=[('military', 'ทหาร'), ('civilian', 'ลูกจ้างประจำ'), ('government', 'พนักงานราชการ')], db_index=True, default='military', max_length=20, verbose_name='ประเภทบุคลากร'),
        ),
        migrations.AlterField(
            model_name='militaryuserprofile',
            name='rank',
            field=models.CharField(blank=True, choices=[('PVT', 'พลทหาร'), ('CPL', 'สิบตรี'), ('SGT3', 'สิบโท'), ('SGT2', 'สิบเอก'), ('SSGT', 'จ่าสิบตรี'), ('MSGT', 'จ่าสิบโท'), ('CSGT', 'จ่าสิบเอก'), ('WO1', 'พันจ่าตรี'), ('WO2', 'พันจ่าโท'), ('WO3', 'พันจ่าเอก'), ('2LT', 'ร้อยตรี'), ('1LT', 'ร้อยโท'), ('CPT', 'ร้อยเอก'), ('MAJ', 'พันตรี'), ('LTCOL', 'พันโท'), ('COL', 'พันเอก'), ('BGEN', 'พลตรี'), ('MGEN', 'พลโท'), ('GEN', 'พลเอก')], default='', max_length=10, verbose_name='ชั้นยศ'),
        ),
    ]
