# Generated by Django 5.2.11 on 2026-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_profile', '0009_militaryuserprofile_civilian_prefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccessPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Course ID (edX)')),
                ('course_type', models.CharField(choices=[('general', 'หลักสูตรทั่วไป'), ('conditional', 'หลักสูตรตามเงื่อนไข')], db_index=True, default='general', max_length=20, verbose_name='ประเภทหลักสูตร')),
                ('allowed_rank_classes', models.CharField(blank=True, default='', max_length=255, verbose_name='ระดับที่เข้าถึงได้')),
                ('prerequisite_course_ids', models.TextField(blank=True, default='', verbose_name='วิชาบังคับก่อน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'นโยบายการเข้าถึงหลักสูตร',
                'verbose_name_plural': 'นโยบายการเข้าถึงหลักสูตร',
            },
        ),
        migrations.AlterField(
            model_name='courserequirement',
            name='rank_class',
            field=models.CharField(choices=[('nco', 'นายทหารประทวน'), ('officer', 'นายทหารสัญญาบัตร'), ('pvt', 'พลทหาร'), ('civilian', 'ลูกจ้างประจำ'), ('government', 'พนักงานราชการ'), ('all', 'ทุกระดับ')], db_index=True, max_length=10, verbose_name='ระดับชั้น'),
        ),
    ]
