# Generated by Django 5.2.11 on 2026-07-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_profile', '0016_optional_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='army_region',
            field=models.CharField(blank=True, choices=[('', 'ไม่ระบุ'), ('1', 'กองทัพภาคที่ 1'), ('2', 'กองทัพภาคที่ 2'), ('3', 'กองทัพภาคที่ 3'), ('4', 'กองทัพภาคที่ 4')], db_index=True, default='', max_length=1, verbose_name='กองทัพภาค'),
        ),
        migrations.AlterField(
            model_name='militaryuserprofile',
            name='rank',
            field=models.CharField(blank=True, choices=[('PVT', 'พลทหาร'), ('CPL', 'สิบตรี'), ('SGT3', 'สิบโท'), ('SGT2', 'สิบเอก'), ('SSGT', 'จ่าสิบตรี'), ('MSGT', 'จ่าสิบโท'), ('CSGT', 'จ่าสิบเอก'), ('CSGT_S', 'จ่าสิบเอกพิเศษ'), ('WO1', 'พันจ่าตรี'), ('WO2', 'พันจ่าโท'), ('WO3', 'พันจ่าเอก'), ('2LT', 'ร้อยตรี'), ('1LT', 'ร้อยโท'), ('CPT', 'ร้อยเอก'), ('MAJ', 'พันตรี'), ('LTCOL', 'พันโท'), ('COL', 'พันเอก'), ('COL_S', 'พันเอกพิเศษ'), ('BGEN', 'พลตรี'), ('MGEN', 'พลโท'), ('GEN', 'พลเอก')], default='', max_length=10, verbose_name='ชั้นยศ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
