# Generated by Django 5.2.11 on 2026-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_profile', '0017_organization_army_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryuserprofile',
            name='army_region',
            field=models.CharField(blank=True, choices=[('', 'ไม่ระบุ'), ('1', 'กองทัพภาคที่ 1'), ('2', 'กองทัพภาคที่ 2'), ('3', 'กองทัพภาคที่ 3'), ('4', 'กองทัพภาคที่ 4'), ('central', 'ส่วนกลาง')], db_index=True, default='', max_length=10, verbose_name='กองทัพภาค'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='army_region',
            field=models.CharField(blank=True, choices=[('', 'ไม่ระบุ'), ('1', 'กองทัพภาคที่ 1'), ('2', 'กองทัพภาคที่ 2'), ('3', 'กองทัพภาคที่ 3'), ('4', 'กองทัพภาคที่ 4'), ('central', 'ส่วนกลาง')], db_index=True, default='', max_length=10, verbose_name='กองทัพภาค'),
        ),
    ]
