# Generated by Django 5.2.11 on 2026-04-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_auth', '0003_pendingregistration_phone_number'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingregistration',
            new_name='military_au_status_7b760d_idx',
            old_name='pending_reg_status_idx',
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='army_region',
            field=models.CharField(blank=True, choices=[('', 'ไม่ระบุ'), ('1', 'ทัพภาคที่ 1'), ('2', 'ทัพภาคที่ 2'), ('3', 'ทัพภาคที่ 3'), ('4', 'ทัพภาคที่ 4')], default='', max_length=1, verbose_name='ทัพภาค'),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='sub_unit',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='หน่วยรอง'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
